version: '3.8'

services:
  lotabots:
    image: lotabots:${TAG:-dev}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - FEATURES=${FEATURES:-"gemini debug"}
    restart: "no"
    environment:
      - RUST_LOG=${RUST_LOG:-debug}
      - ENVIRONMENT=development
    volumes:
      - .:/workspace:cached
      - ./config:/opt/lotabots/config:ro
      - data:/opt/lotabots/data
      - cargo-cache:/usr/local/cargo/registry
    deploy:
      resources:
        limits:
          cpus: '0' # No CPU limits in debug mode
          memory: 16G
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - lotabots-net

volumes:
  data:
    name: lotabots-debug-data
  cargo-cache:
    name: cargo-cache

networks:
  lotabots-net:
    name: lotabots-debug-network
    driver: bridge
